# Functional programming 



## [numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)](https://numpy.org/devdocs//reference/generated/numpy.apply_along_axis.html)
Apply a function to 1-D slices along the given axis.

In [2]:
import numpy as np

def my_func(a):
    """ Average first and last element of a 1-D array """
    return (a[0] + a[-1])*0.5

b = np.arange(9).reshape((3,3))
print(b)
np.apply_along_axis(my_func, 0, b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([3., 4., 5.])

In [4]:
np.apply_along_axis(my_func, 1, b)

array([1., 4., 7.])

In [5]:
b = np.array([[8,1,7], [4,3,9], [5,2,6]])
np.apply_along_axis(sorted, 1, b)

array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 6]])

see also [apply_over_axes](https://numpy.org/devdocs//reference/generated/numpy.apply_over_axes.html#numpy.apply_over_axes)

## [numpy.piecewise(x, condlist, funclist, *args, **kw)](https://numpy.org/devdocs//reference/generated/numpy.piecewise.html)

Evaluate a piecewise-defined function.

Given a set of conditions and corresponding functions, evaluate each function on the input data wherever its condition is true.

In [7]:
x = np.linspace(-2.5, 2.5, 6)
np.piecewise(x, [x<0, x>=0], [-1, 1])

array([-1., -1., -1.,  1.,  1.,  1.])

In [8]:
np.piecewise(x, [x<0, x>=0], [lambda x: -x, lambda x:x])

array([2.5, 1.5, 0.5, 0.5, 1.5, 2.5])